export const MUSIC = [
    {
        album: 'kingdom',
        key: 'musicOutskirts',
        title: 'Kingdom Outskirts',
        condition: 'Pass through the Kingdom Outskirts on Lunar without taking damage',
        icon: '//static.wikitide.net/rnswiki/6/6f/Area_Kingdom_Outskirts.png',
    },
    {
        album: 'kingdom',
        key: 'musicLighthouse',
        title: 'Red Darkhouse',
        condition: 'Defeat Ranalie, the Mythril Dragon, while she is dashing through the arena',
        icon: '//static.wikitide.net/rnswiki/3/33/Area_Red_Darkhouse.png',
    },
    {
        album: 'kingdom',
        key: 'musicNest',
        title: "Scholar's Nest",
        condition: 'Defeat Twili, the Valedictorian Crow, while you are stopped in time',
        icon: '//static.wikitide.net/rnswiki/7/70/Area_Scholar%27s_Nest.png',
    },
    {
        album: 'kingdom',
        key: 'musicArsenal',
        title: "King's Arsenal",
        condition: 'Defeat Merran, the Steeltooth Wolf, while time is slowed',
        icon: '//static.wikitide.net/rnswiki/b/b3/Area_King%27s_Arsenal.png',
    },
    {
        album: 'kingdom',
        key: 'musicStreets',
        title: 'Churchmouse Streets',
        condition: 'Defeat Matti, the Paladin Mouse, while her guard is up',
        icon: '//static.wikitide.net/rnswiki/9/97/Area_Churchmouse_Streets.png',
    },
    {
        album: 'kingdom',
        key: 'musicLakeside',
        title: 'Emerald Lakeside',
        condition: 'Defeat Avy, the Starry Frog, without standing still for longer than 5 seconds',
        icon: '//static.wikitide.net/rnswiki/0/00/Area_Emerald_Lakeside.png',
    },
    {
        album: 'kingdom',
        key: 'musicKeep',
        title: 'The Pale Keep',
        condition: 'Pass through the Pale Keep on Lunar without taking damage',
        icon: '//static.wikitide.net/rnswiki/3/35/Spr_item_swiftflight_6.png',
    },
    {
        album: 'kingdom',
        key: 'musicBossSerious',
        title: 'A Serious Battle',
        condition: 'Win a run on Normal difficulty or above without opening treasure chests',
        icon: '//static.wikitide.net/rnswiki/5/55/Spr_item_flame_3.png',
    },
    {
        album: 'kingdom',
        key: 'musicBossMysterious',
        title: 'A Mysterious Battle',
        condition: 'Win a run on Normal difficulty or above without talking to a shopkeeper',
        icon: '//static.wikitide.net/rnswiki/1/18/Spr_item_arcane_4.png',
    },
    {
        album: 'kingdom',
        key: 'musicBossJustice',
        title: 'A Valiant Battle',
        condition: 'Win a run on Hard difficulty or above without a destination chosen at the start',
        icon: '//static.wikitide.net/rnswiki/3/32/Spr_item_shrine_0.png',
    },
    {
        album: 'kingdom',
        key: 'musicPinnacle',
        title: 'The Moonlit Pinnacle',
        condition: 'Win a run on Normal difficulty or above without taking damage',
        icon: '//static.wikitide.net/rnswiki/9/9b/Area_Moonlit_Pinnacle.png',
    },
    {
        album: 'kingdom',
        key: 'musicEnding',
        title: 'A Bittersweet End',
        condition: 'Save Shira from the Spell',
        icon: '//static.wikitide.net/rnswiki/2/2d/Spr_item_life_0.png',
    },
    {
        album: 'extra',
        key: 'musicGeode',
        title: 'Crack in the Geode',
        condition: 'Pass through the Crack in the Geode on Lunar without taking damage',
        icon: '//static.wikitide.net/rnswiki/a/a0/Area_Crack_In_The_Geode.png',
    },
    {
        album: 'extra',
        key: 'musicDepths',
        title: 'Darkhouse Depths',
        condition: 'Defeat Farrah, the Witch\'s Hound, while standing in her "Deathwall"',
        icon: '//static.wikitide.net/rnswiki/b/bb/Area_Darkhouse_Depths.png',
    },
    {
        album: 'extra',
        key: 'musicSanct',
        title: 'Subterra Sanctum',
        condition: 'On Normal difficulty or above, defeat every butterfly spawned by Eternal Bloom',
        icon: '//static.wikitide.net/rnswiki/3/31/Area_Subterra_Sanctum.png',
    },
    {
        album: 'extra',
        key: 'musicAurum',
        title: 'Atelier Aurum',
        condition: 'On Normal difficulty or above, defeat Asha without anyone spending any gold previously in the run',
        icon: '//static.wikitide.net/rnswiki/4/48/Area_Atelier_Aurum.png',
    },
    {
        album: 'extra',
        key: 'musicDarkhall',
        title: 'Looping Hallway',
        condition: 'On Normal difficulty or above, defeat a Spelllock enemy in less than 10 seconds.',
        icon: '//static.wikitide.net/rnswiki/7/76/Area_Looping_Hallway.png',
    },
    {
        album: 'extra',
        key: 'musicBossHound',
        title: "Fantasia for the Witch's Hound",
        condition: 'Collect 8 kinds of small creature trinkets',
        icon: '//static.wikitide.net/rnswiki/d/d4/Spr_item_sharpedge_7.png',
    },
    {
        album: 'extra',
        key: 'musicBossOwl',
        title: "Rondo for the Witch's Messenger",
        condition: 'Collect 5 kinds of floofball',
        icon: '',
    },
    {
        album: 'extra',
        key: 'musicBossCat',
        title: "Etude for the Witch's Familiar",
        condition: 'Collect 50 trinkets',
        icon: '//static.wikitide.net/rnswiki/7/7e/Spr_item_performers_1.png',
    },
    {
        album: 'extra',
        key: 'musicReflection',
        title: "Overture for the Witch's Heart",
        condition: 'See your adventure through to its resolution',
        icon: '',
    },
    {
        album: 'extra',
        key: 'musicReflection2',
        title: 'Woven Into a Spell',
        condition: 'Get all Adept/Challenger palettes',
        icon: '',
    },
    {
        album: 'kingdom',
        key: 'musicLakesideOffVocal',
        title: 'Emerald Lakeside (Off Vocal)',
        condition: 'Win a run on Normal difficulty or above in less than 30 minutes',
        icon: '//static.wikitide.net/rnswiki/e/e9/Spr_item_ruins_7.png',
    },
    {
        album: 'extra',
        key: 'musicSanctOffVocal',
        title: 'Subterra Sanctum (Off Vocal)',
        condition: 'Unlock every item set',
        icon: '//static.wikitide.net/rnswiki/a/ab/Spr_item_teaparty_5.png',
    },
    {
        album: 'extra',
        key: 'musicReflection2OffVocal',
        title: 'Woven into a Spell (Off Vocal)',
        condition: 'Win a run with every loot item at least once',
        icon: '',
    },
];
