export const MUSIC = [
    {
        album: 'kingdom',
        key: 'musicOutskirts',
        title: 'Kingdom Outskirts',
        condition: 'Pass through the Kingdom Outskirts on Lunar without taking damage',
    },
    {
        album: 'kingdom',
        key: 'musicNest',
        title: "Scholar's Nest",
        condition: 'Defeat Twili, the Valedictorian Crow, while you are stopped in time',
    },
    {
        album: 'kingdom',
        key: 'musicArsenal',
        title: "King's Arsenal",
        condition: 'Defeat Merran, the Steeltooth Wolf, while time is slowed',
    },
    {
        album: 'kingdom',
        key: 'musicLighthouse',
        title: 'Red Darkhouse',
        condition: 'Defeat Ranalie, the Mythril Dragon, while she is dashing through the arena',
    },
    {
        album: 'kingdom',
        key: 'musicStreets',
        title: 'Churchmouse Streets',
        condition: 'Defeat Matti, the Paladin Mouse, while her guard is up',
    },
    {
        album: 'kingdom',
        key: 'musicLakeside',
        title: 'Emerald Lakeside',
        condition: 'Defeat Avy, the Starry Frog, without standing still for longer than 5 seconds',
    },
    {
        album: 'kingdom',
        key: 'musicKeep',
        title: 'The Pale Keep',
        condition: 'Pass through the Pale Keep on Lunar without taking damage',
    },
    {
        album: 'kingdom',
        key: 'musicPinnacle',
        title: 'The Moonlit Pinnacle',
        condition: 'Win a run on Normal difficulty or above without taking damage',
    },
    {
        album: 'kingdom',
        key: 'musicBossSerious',
        title: 'A Serious Battle',
        condition: 'Win a run on Normal difficulty or above without opening treasure chests',
    },
    {
        album: 'kingdom',
        key: 'musicBossMysterious',
        title: 'A Mysterious Battle',
        condition: 'Win a run on Normal difficulty or above without talking to a shopkeeper',
    },
    {
        album: 'kingdom',
        key: 'musicBossJustice',
        title: 'A Valiant Battle',
        condition: 'Win a run on Hard difficulty or above without a destination chosen at the start',
    },
    {
        album: 'kingdom',
        key: 'musicEnding',
        title: 'A Bittersweet End',
        condition: 'Save Shira from the Spell',
    },
    {
        album: 'kingdom',
        key: 'musicLakesideOffVocal',
        title: 'Emerald Lakeside (Off Vocal)',
        condition: 'Win a run on Normal difficulty or above in less than 30 minutes',
    },
    {
        album: 'extra',
        key: 'musicGeode',
        title: 'Crack in the Geode',
        condition: 'Pass through the Crack in the Geode on Lunar without taking damage',
    },
    {
        album: 'extra',
        key: 'musicDepths',
        title: 'Darkhouse Depths',
        condition: 'Defeat Farrah, the Witch\'s Hound, while standing in her "Deathwall"',
    },
    {
        album: 'extra',
        key: 'musicSanct',
        title: 'Subterra Sanctum',
        condition: 'On Normal difficulty or above, defeat every butterfly spawned by Eternal Bloom',
    },
    {
        album: 'extra',
        key: 'musicAurum',
        title: 'Atelier Aurum',
        condition: 'On Normal difficulty or above, defeat Asha without anyone spending any gold previously in the run',
    },
    {
        album: 'extra',
        key: 'musicDarkhall',
        title: 'Looping Hallway',
        condition: 'On Normal difficulty or above, defeat a Spelllock enemy in less than 10 seconds.',
    },
    {
        album: 'extra',
        key: 'musicBossHound',
        title: "Fantasia for the Witch's Hound",
        condition: 'Collect 8 kinds of small creature trinkets',
    },
    {
        album: 'extra',
        key: 'musicBossOwl',
        title: "Rondo for the Witch's Messenger",
        condition: 'Collect 5 kinds of floofball',
    },
    { album: 'extra', key: 'musicBossCat', title: "Etude for the Witch's Familiar", condition: 'Collect 50 trinkets' },
    {
        album: 'extra',
        key: 'musicReflection',
        title: "Overture for the Witch's Heart",
        condition: 'See your adventure through to its resolution',
    },
    {
        album: 'extra',
        key: 'musicReflection2',
        title: 'Woven Into a Spell',
        condition: 'Get all Adept/Challenger palettes',
    },
    {
        album: 'extra',
        key: 'musicSanctOffVocal',
        title: 'Subterra Sanctum (Off Vocal)',
        condition: 'Unlock every item set',
    },
    {
        album: 'extra',
        key: 'musicReflection2OffVocal',
        title: 'Woven into a Spell (Off Vocal)',
        condition: 'Win a run with every loot item at least once',
    },
];
